doc: [] `useSDK` readme
contentful/create-contentful-app pull request #927
Opened 2022-03-10 14:18 UTC by loweisz

Add a small section to the readme about the new hook

2022-03-10 15:30 UTC, Jwhiles commented on packages/contentful--react-apps-toolkit/README.md
> +This hook returns the appSDK. You can inject it anywhere in your Contentful app.
```suggestion
This hook returns the appSDK. 
```

2022-03-10 15:31 UTC, Jwhiles commented on packages/contentful--react-apps-toolkit/README.md
> +The only requirement for using it is that the component that uses it is wrapped within the `SDKProvider`, which ideally should be
I'd say remove the sentence

"which ideally should be located in the core of your application (e.g. `index.tsx`). "

As long as they only use the hooks inside the provider, it's up to the developer where the provider is located.

2022-03-10 15:31 UTC, Jwhiles requested changes
some nits

2022-03-16 10:23 UTC, andipaetzold approved these changes

2022-03-16 10:28 UTC, merged